version: "3.8"

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  service-a:
    build: ./service-a
    ports:
      - "8080:8080"
    depends_on:
      - zipkin

  service-b:
    build: ./service-b
    ports:
      - "8081:8081"
    depends_on:
      - zipkin