services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  service-a:
    build: ./service_a
    ports:
      - "8080:8080"
    depends_on:
      - zipkin

  service-b:
    build: ./service_b
    ports:
      - "8081:8081"
    depends_on:
      - zipkin